env:
  browser: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
plugins:
  - 'react-hooks'
settings:
  react:
    version: "18.3"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  no-console: warn
  react/prop-types: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
