import json
import re
from pathlib import Path

DIST_DIR = Path(__file__).parent / 'static/dist'
DIST_URL = Path('/static/dist')


def webpack_chunks(entrypoint, file_suffix):
    """
    Yield URLs of chunks to include for an `entrypoint`.
    Get the list of output chunks from manifest generated by webpack.
    """
    manifest_path = DIST_DIR / 'manifest.json'
    manifest_raw = manifest_path.read_text()
    manifest = json.loads(manifest_raw)
    for file_url_path in manifest[entrypoint]:
        if file_url_path.endswith(file_suffix):
            yield file_url_path


def webpack_scripts(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.js')


def webpack_styles(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.css')
