import json
import re
from pathlib import Path

DIST_DIR = Path(__file__).parent / 'static/dist'
DIST_URL = Path('/static/dist')

def webpack_scripts(entrypoint: str):
    """Yield URLs of scripts to include for an `entrypoint`

    Get the list of output chunks from manifest generated by webpack.
    Guess which chunks concern this `entrypoint` from the chunk filename.
    """
    manifest_path = DIST_DIR / 'stats.json'
    manifest_raw = manifest_path.read_text()
    manifest = json.loads(manifest_raw)
    assets = manifest['entrypoints'][entrypoint]['assets']
    for asset in assets:
        if not asset.endswith('.js'):
            continue
        yield str(DIST_URL / asset)
