import json
import re
from pathlib import Path

DIST_DIR = Path(__file__).parent / 'static/dist'
DIST_URL = Path('/static/dist')


def webpack_chunks(entrypoint, file_suffix):
    """Yield URLs of chunks to include for an `entrypoint`

    Get the list of output chunks from manifest generated by webpack.
    Guess which chunks concern this `entrypoint` from the chunk filename.
    """
    manifest_path = DIST_DIR / 'manifest.json'
    manifest_raw = manifest_path.read_text()
    manifest = json.loads(manifest_raw)
    for infile, outfile in manifest.items():
        if not outfile.endswith(file_suffix):
            continue
        fname = infile.split('.')[0]
        parts = fname.split('~')
        if entrypoint in parts:
            yield str(DIST_URL / outfile)


def webpack_scripts(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.bundle.js')


def webpack_styles(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.bundle.css')
